# Generated by Django 4.0.5 on 2022-06-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='phone_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='portfolio',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='skils',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
